package com.tfhk.cfgfolder.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * CfgFolder generated by hbm2java
 */
public class CfgFolder implements java.io.Serializable {

	private CfgFolderId id;
	private String folderName;
	private String rootPath;
	private Date updateDate;
	private Date createDate;
	private String fileType;

	public CfgFolder() {
	}

	public CfgFolder(CfgFolderId id, String folderName) {
		this.id = id;
		this.folderName = folderName;
	}

	public CfgFolder(CfgFolderId id, String folderName, String rootPath, Date updateDate, Date createDate,
			String fileType) {
		this.id = id;
		this.folderName = folderName;
		this.rootPath = rootPath;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.fileType = fileType;
	}

	public CfgFolderId getId() {
		return this.id;
	}

	public void setId(CfgFolderId id) {
		this.id = id;
	}

	public String getFolderName() {
		return this.folderName;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	public String getRootPath() {
		return this.rootPath;
	}

	public void setRootPath(String rootPath) {
		this.rootPath = rootPath;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
