package com.tfhk.cfgfolder.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

/**
 * CfgFolderId generated by hbm2java
 */
public class CfgFolderId implements java.io.Serializable {

	private String folderPath;
	private String account;

	public CfgFolderId() {
	}

	public CfgFolderId(String folderPath, String account) {
		this.folderPath = folderPath;
		this.account = account;
	}

	public String getFolderPath() {
		return this.folderPath;
	}

	public void setFolderPath(String folderPath) {
		this.folderPath = folderPath;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CfgFolderId))
			return false;
		CfgFolderId castOther = (CfgFolderId) other;

		return ((this.getFolderPath() == castOther.getFolderPath()) || (this.getFolderPath() != null
				&& castOther.getFolderPath() != null && this.getFolderPath().equals(castOther.getFolderPath())))
				&& ((this.getAccount() == castOther.getAccount()) || (this.getAccount() != null
						&& castOther.getAccount() != null && this.getAccount().equals(castOther.getAccount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolderPath() == null ? 0 : this.getFolderPath().hashCode());
		result = 37 * result + (getAccount() == null ? 0 : this.getAccount().hashCode());
		return result;
	}

}
