package com.tfhk.cfgrootpath.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

/**
 * CfgRootpathMapping generated by hbm2java
 */
public class CfgRootpathMapping implements java.io.Serializable {

	private CfgRootpathMappingId id;
	private String fileType;

	public CfgRootpathMapping() {
	}

	public CfgRootpathMapping(CfgRootpathMappingId id) {
		this.id = id;
	}

	public CfgRootpathMapping(CfgRootpathMappingId id, String fileType) {
		this.id = id;
		this.fileType = fileType;
	}

	public CfgRootpathMappingId getId() {
		return this.id;
	}

	public void setId(CfgRootpathMappingId id) {
		this.id = id;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
