package com.tfhk.cfgparam.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

/**
 * CfgParam generated by hbm2java
 */
public class CfgParam implements java.io.Serializable {

	private String code;
	private String codeName;
	private String codeValue;
	private String codeDesc;

	public CfgParam() {
	}

	public CfgParam(String code) {
		this.code = code;
	}

	public CfgParam(String code, String codeName, String codeValue, String codeDesc) {
		this.code = code;
		this.codeName = codeName;
		this.codeValue = codeValue;
		this.codeDesc = codeDesc;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

}
