package com.tfhk.cfguser.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

/**
 * CfgUser generated by hbm2java
 */
public class CfgUser implements java.io.Serializable {

	private String account;
	private String nameEn;
	private String nameCh;
	private String password;

	public CfgUser() {
	}

	public CfgUser(String account, String password) {
		this.account = account;
		this.password = password;
	}

	public CfgUser(String account, String nameEn, String nameCh, String password) {
		this.account = account;
		this.nameEn = nameEn;
		this.nameCh = nameCh;
		this.password = password;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getNameCh() {
		return this.nameCh;
	}

	public void setNameCh(String nameCh) {
		this.nameCh = nameCh;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
