package com.tfhk.curfile.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * CurFile generated by hbm2java
 */
public class CurFile implements java.io.Serializable {

	private CurFileId id;
	private String fileName;
	private String folderPath;
	private String mineType;
	private Date updateDate;
	private Date uploadDate;
	private String fileType;

	public CurFile() {
	}

	public CurFile(CurFileId id, String fileName) {
		this.id = id;
		this.fileName = fileName;
	}

	public CurFile(CurFileId id, String fileName, String folderPath, String mineType, Date updateDate, Date uploadDate,
			String fileType) {
		this.id = id;
		this.fileName = fileName;
		this.folderPath = folderPath;
		this.mineType = mineType;
		this.updateDate = updateDate;
		this.uploadDate = uploadDate;
		this.fileType = fileType;
	}

	public CurFileId getId() {
		return this.id;
	}

	public void setId(CurFileId id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFolderPath() {
		return this.folderPath;
	}

	public void setFolderPath(String folderPath) {
		this.folderPath = folderPath;
	}

	public String getMineType() {
		return this.mineType;
	}

	public void setMineType(String mineType) {
		this.mineType = mineType;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
