package com.tfhk.curfile.model;
// Generated 2018/1/28 �U�� 03:06:37 by Hibernate Tools 5.2.8.Final

/**
 * CurFileId generated by hbm2java
 */
public class CurFileId implements java.io.Serializable {

	private String filePath;
	private String account;

	public CurFileId() {
	}

	public CurFileId(String filePath, String account) {
		this.filePath = filePath;
		this.account = account;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CurFileId))
			return false;
		CurFileId castOther = (CurFileId) other;

		return ((this.getFilePath() == castOther.getFilePath()) || (this.getFilePath() != null
				&& castOther.getFilePath() != null && this.getFilePath().equals(castOther.getFilePath())))
				&& ((this.getAccount() == castOther.getAccount()) || (this.getAccount() != null
						&& castOther.getAccount() != null && this.getAccount().equals(castOther.getAccount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFilePath() == null ? 0 : this.getFilePath().hashCode());
		result = 37 * result + (getAccount() == null ? 0 : this.getAccount().hashCode());
		return result;
	}

}
