package com.tfhk.jpa.model;
// Generated 2018/2/2 �U�� 02:52:19 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CfgParam generated by hbm2java
 */
@Entity
@Table(name = "cfg_param", schema = "TFHK")
public class CfgParam implements java.io.Serializable {

	private String code;
	private String codeName;
	private String codeValue;
	private String codeDesc;

	public CfgParam() {
	}

	public CfgParam(String code) {
		this.code = code;
	}

	public CfgParam(String code, String codeName, String codeValue, String codeDesc) {
		this.code = code;
		this.codeName = codeName;
		this.codeValue = codeValue;
		this.codeDesc = codeDesc;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CODE_NAME", length = 50)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "CODE_VALUE", length = 50)
	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	@Column(name = "CODE_DESC", length = 50)
	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

}
