package com.tfhk.jpa.model;
// Generated 2018/2/2 �U�� 02:52:19 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CfgRootpathMapping generated by hbm2java
 */
@Entity
@Table(name = "cfg_rootpath_mapping", schema = "TFHK")
public class CfgRootpathMapping implements java.io.Serializable {

	private CfgRootpathMappingId id;
	private String fileType;

	public CfgRootpathMapping() {
	}

	public CfgRootpathMapping(CfgRootpathMappingId id) {
		this.id = id;
	}

	public CfgRootpathMapping(CfgRootpathMappingId id, String fileType) {
		this.id = id;
		this.fileType = fileType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rootPath", column = @Column(name = "ROOT_PATH", nullable = false, length = 50)),
			@AttributeOverride(name = "account", column = @Column(name = "account", nullable = false, length = 30)) })
	public CfgRootpathMappingId getId() {
		return this.id;
	}

	public void setId(CfgRootpathMappingId id) {
		this.id = id;
	}

	@Column(name = "FILE_TYPE", length = 50)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
