package com.tfhk.jpa.model;
// Generated 2018/2/2 �U�� 02:52:19 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CfgUser generated by hbm2java
 */
@Entity
@Table(name = "cfg_user", schema = "TFHK")
public class CfgUser implements java.io.Serializable {

	private String account;
	private String nameEn;
	private String nameCh;
	private String password;

	public CfgUser() {
	}

	public CfgUser(String account, String password) {
		this.account = account;
		this.password = password;
	}

	public CfgUser(String account, String nameEn, String nameCh, String password) {
		this.account = account;
		this.nameEn = nameEn;
		this.nameCh = nameCh;
		this.password = password;
	}

	@Id

	@Column(name = "account", unique = true, nullable = false, length = 30)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "name_en", length = 50)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "name_ch", length = 50)
	public String getNameCh() {
		return this.nameCh;
	}

	public void setNameCh(String nameCh) {
		this.nameCh = nameCh;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
