package com.tfhk.jpa.model;
// Generated 2018/2/2 �U�� 02:52:19 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurFile generated by hbm2java
 */
@Entity
@Table(name = "cur_file", schema = "TFHK")
public class CurFile implements java.io.Serializable {

	private CurFileId id;
	private String fileName;
	private String folderPath;
	private String mineType;
	private Date updateDate;
	private Date uploadDate;
	private String fileType;

	public CurFile() {
	}

	public CurFile(CurFileId id, String fileName) {
		this.id = id;
		this.fileName = fileName;
	}

	public CurFile(CurFileId id, String fileName, String folderPath, String mineType, Date updateDate, Date uploadDate,
			String fileType) {
		this.id = id;
		this.fileName = fileName;
		this.folderPath = folderPath;
		this.mineType = mineType;
		this.updateDate = updateDate;
		this.uploadDate = uploadDate;
		this.fileType = fileType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "filePath", column = @Column(name = "FILE_PATH", nullable = false, length = 50)),
			@AttributeOverride(name = "account", column = @Column(name = "account", nullable = false, length = 30)) })
	public CurFileId getId() {
		return this.id;
	}

	public void setId(CurFileId id) {
		this.id = id;
	}

	@Column(name = "FILE_NAME", nullable = false, length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FOLDER_PATH", length = 50)
	public String getFolderPath() {
		return this.folderPath;
	}

	public void setFolderPath(String folderPath) {
		this.folderPath = folderPath;
	}

	@Column(name = "mine_type", length = 50)
	public String getMineType() {
		return this.mineType;
	}

	public void setMineType(String mineType) {
		this.mineType = mineType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", length = 10)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "upload_date", length = 10)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "FILE_TYPE", length = 50)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
